workflow:
  rules:
    - if: $CI_COMMIT_BRANCH =~ /-WIP$/
      when: never
    - when: always

variables:
  GIT_STRATEGY: fetch
  REGISTRY: registry.gitlab.com
  APPLICATION: mhm2
  TEST_IMAGE: $REGISTRY/$REGISTRY_USER/$APPLICATION:latest
  RELEASE_IMAGE: $REGISTRY/$REGISTRY_USER/$APPLICATION:$CI_BUILD_REF_NAME
  HULK_UPCXX_VER: 2021.3.0

stages:
  - build
  - validation
  - accuracy

#
# cori
#

Cori:build:
  stage: build
  tags:
    - Cori
  script:
    - set -e
    - set -x
    - git submodule init
    - git submodule sync
    - git submodule update
    - uname -a
    - pwd
    - date
    - echo "Establishing variables"
    - export MHM2_SOURCE=$(pwd)
    - export BASE=${SCRATCH}/tmp/gitlab-runner-scratch-Cori-mhm2-${USER}
    - export SCRATCH=${BASE}/mhm2-${CI_COMMIT_SHORT_SHA}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_TAG}
    - export INSTALL_PREFIX=${SCRATCH}/install
    - export BUILD_PREFIX=${SCRATCH}/build
    - export RUN_PREFIX=${SCRATCH}/runs
    - echo "BASE=${BASE} SCRATCH=${SCRATCH}"
    - mkdir -p ${BASE}
    - rm -rf ${SCRATCH}
    - echo "Cleaning out old installs"
    - find ${BASE} -maxdepth 1  -name 'mhm*'  -mtime +4 -type d -exec rm -rf '{}' ';' || /bin/true
    - mkdir -p ${SCRATCH} ${RUN_PREFIX}
    - exec >  >(tee -ia ${SCRATCH}/build.log)
    - exec 2> >(tee -ia ${SCRATCH}/build.err >&2)    
    - echo "Logging to ${SCRATCH}/build.log and .err at $(date) on $(uname -n) in $(pwd)"
    - lmstat -a -c $INTEL_LICENSE_FILE || /bin/true
    - echo "Loading Haswell modules for upcxx GNU"
    - source ${MHM2_SOURCE}/contrib/environments/cori-haswell/gnu.sh
    - module list
    - export MHM2_BUILD=${BUILD_PREFIX}-haswell-dbg
    - mkdir -p ${MHM2_BUILD}
    - cd $MHM2_BUILD
    - echo "Building Haswell GNU Debug"
    - CXX=CC cmake -DCMAKE_INSTALL_PREFIX=${INSTALL_PREFIX}-haswell -DCMAKE_BUILD_TYPE=Debug ${MHM2_SOURCE}
    - make -j 12 all check install
    - export MHM2_BUILD=${BUILD_PREFIX}-haswell
    - mkdir -p ${MHM2_BUILD}
    - cd $MHM2_BUILD
    - echo "Building Haswell GNU Release"
    - CXX=CC cmake -DCMAKE_INSTALL_PREFIX=${INSTALL_PREFIX}-haswell -DCMAKE_BUILD_TYPE=Release ${MHM2_SOURCE}
    - make -j 12 all check install
    - echo "Loading KNL modules for upcxx on cori GNU"
    - source ${MHM2_SOURCE}/contrib/environments/cori-knl/gnu.sh
    - module list
    - export MHM2_BUILD=${BUILD_PREFIX}-knl-dbg
    - mkdir -p ${MHM2_BUILD}
    - cd $MHM2_BUILD
    - echo "Building KNL GNU Debug"
    - CXX=CC cmake -DCMAKE_INSTALL_PREFIX=${INSTALL_PREFIX}-knl-dbg -DCMAKE_BUILD_TYPE=Debug ${MHM2_SOURCE}
    - make -j 12 all install # cannot check knl build on haswell
    - export MHM2_BUILD=${BUILD_PREFIX}-knl-rwdi
    - mkdir -p ${MHM2_BUILD}
    - cd $MHM2_BUILD
    - echo "Building KNL GNU RelWithDebInfo"
    - CXX=CC cmake -DCMAKE_INSTALL_PREFIX=${INSTALL_PREFIX}-knl-rwdi -DCMAKE_BUILD_TYPE=RelWithDebInfo ${MHM2_SOURCE}
    - make -j 12 all install # cannot check knl build on haswell
    - export MHM2_BUILD=${BUILD_PREFIX}-knl
    - mkdir -p ${MHM2_BUILD}
    - cd $MHM2_BUILD
    - echo "Building KNL GNU Release"
    - CXX=CC cmake -DCMAKE_INSTALL_PREFIX=${INSTALL_PREFIX}-knl -DCMAKE_BUILD_TYPE=Release ${MHM2_SOURCE}
    - make -j 12 all install # cannot check knl build on haswell
    - echo "Done building"

Cori:validation:
  stage: validation
  tags:
    - Cori
  script:
    - set -e
    - set -x
    - uname -a
    - pwd
    - date
    - export GASNET_BACKTRACE=1
    - echo "Establishing variables"
    - export MHM2_SOURCE=$(pwd)
    - export BASE=${SCRATCH}/tmp/gitlab-runner-scratch-Cori-mhm2-${USER}
    - export SCRATCH=${BASE}/mhm2-${CI_COMMIT_SHORT_SHA}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_TAG}
    - export INSTALL_PREFIX=${SCRATCH}/install
    - export BUILD_PREFIX=${SCRATCH}/build
    - export RUN_PREFIX=${SCRATCH}/runs
    - echo "BASE=${BASE} SCRATCH=${SCRATCH}"
    - echo "Loading KNL modules for upcxx on cori"
    - source ${MHM2_SOURCE}/contrib/environments/cori-knl/gnu.sh
    - module list
    - cd $SCRATCH
    - exec >  >(tee -ia ${SCRATCH}/validation.log)
    - exec 2> >(tee -ia ${SCRATCH}/validation.err >&2)   
    - echo "Logging to ${SCRATCH}/validation.log and .err at $(date) on $(uname -n) in $(pwd)"
    - FAILED=""   
    - inst=${INSTALL_PREFIX}-knl
    - echo "Testing builds on KNL - $inst"
    - export RWDI=${INSTALL_PREFIX}-knl-rwdi/bin/
    - export DBG=${INSTALL_PREFIX}-knl-dbg/bin/
    - export REL=${INSTALL_PREFIX}-knl/bin/
    - export ARCTIC=/global/cscratch1/sd/regan/GitlabCIData/
    - export OPTS="-r ${ARCTIC}/arctic_sample_0.fq -v --checkpoint=yes"
    - export GASNET_BACKTRACE=1

    - echo "Submitting job on 3 nodes - on 2 nodes roughly RWDI=400s, DBG --kmer-lens 63 =456s  ...REL=170s"
    - knl_job=$(sbatch --parsable --job-name="CImhv-${CI_COMMIT_SHORT_SHA}" --account=mp215 -C knl --nodes=3 --qos=debug --time=30:00 --wrap="${RWDI}/mhm2.py $OPTS -o ${RUN_PREFIX}/rwdi && ${DBG}/mhm2.py ${OPTS} --kmer-lens 63 -o ${RUN_PREFIX}/dbg && echo Good")
    - echo "Waiting for knl job $knl_job"
    - date
    - while /bin/true ; do sleep 120 ; date ; sacct=$(sacct -j $knl_job -o state -X -n 2>/dev/null || true) ; if [ -n "${sacct}" -a -z "$(echo "${sacct}" | grep ING)" ] ; then break ; fi ; done
    - echo "sacct $sacct"
    - sacct=$(sacct -j $knl_job -X -n)
    - echo "sacct $sacct"
    - cat slurm-${knl_job}.out
    - wasgood=$(echo "${sacct}" | grep -v '0:0' || true)
    - if [ -z "$wasgood" ] ; then  true ; else  echo "knl job ${knl_job} failed somehow - ${wasgood}"; false ; fi
    - if [ ! -f ${RUN_PREFIX}/rwdi/final_assembly.fasta ] ; then FAILED="${FAILED} Did not find final_assembly.fasta on rwdi" ; fi
    - ${RWDI}/check_asm_quality.py --asm-dir ${RUN_PREFIX}/rwdi --expected-quals ${RWDI}/../share/good-arctic-sample0.txt --refs ${ARCTIC}/arcticsynth-refs.fa || FAILED="${FAILED} Did not pass check_asm_quality.py on rwdi"
    - if [ ! -f ${RUN_PREFIX}/dbg/final_assembly.fasta ] ; then FAILED="${FAILED} Did not find final_assembly.fasta on dbg" ; fi
    - ${RWDI}/check_asm_quality.py --asm-dir ${RUN_PREFIX}/dbg --expected-quals ${RWDI}/../share/good-arctic-sample0-k63.txt --refs ${ARCTIC}/arcticsynth-refs.fa || echo "WARN Did not pass check_asm_quality.py on dbg with reduced workflow k63"
    - if [ -z "$FAILED" ] ; then  true ; else echo "Something failed somehow - ${FAILED}"; false ; fi
    - echo "Completed"

Cori:accuracy:
  stage: accuracy
  tags:
    - Cori
  script:
    - set -e
    - set -x
    - uname -a
    - pwd
    - date
    - export GASNET_BACKTRACE=1
    - echo "Establishing variables"
    - export MHM2_SOURCE=$(pwd)
    - export BASE=${SCRATCH}/tmp/gitlab-runner-scratch-Cori-mhm2-${USER}
    - export SCRATCH=${BASE}/mhm2-${CI_COMMIT_SHORT_SHA}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_TAG}
    - export INSTALL_PREFIX=${SCRATCH}/install
    - export BUILD_PREFIX=${SCRATCH}/build
    - export RUN_PREFIX=${SCRATCH}/runs
    - echo "BASE=${BASE} SCRATCH=${SCRATCH}"
    - echo "Loading KNL modules for upcxx on cori"
    - source ${MHM2_SOURCE}/contrib/environments/cori-knl/gnu.sh
    - exec >  >(tee -ia ${SCRATCH}/accuracy.log)
    - exec 2> >(tee -ia ${SCRATCH}/accuracy.err >&2)
    - echo "Logging to ${SCRATCH}/accuracy.log and .err at $(date) on $(uname -n) in $(pwd)"    
    - module list
    - cd $SCRATCH
    - FAILED=""
    - echo "Testing accuracy"
    - export REL=${INSTALL_PREFIX}-knl/bin/
    - export ARCTIC=/global/cscratch1/sd/regan/GitlabCIData/
    - export OPTS="-r ${ARCTIC}/arctic_sample_0.fq --checkpoint=no"
    - echo "Submitting job on 5 nodes... on 2 nodes is is roughly REL=170s"
    - knl_job=$(sbatch --parsable --job-name="CImha-${CI_COMMIT_SHORT_SHA}" --account=mp215 -C knl --nodes=5 --qos=debug --time=10:00 --wrap="${REL}/mhm2.py $OPTS -o ${RUN_PREFIX}/rel && echo Good")
    - echo "Submitting full arctic job on 15 nodes"
    - export OPTS2="-r ${ARCTIC}/arctic_samples.fq --checkpoint=no"
    - knl_job2=$(sbatch --parsable --job-name="CI-mhm2-${CI_COMMIT_SHORT_SHA}" --account=mp215 -C knl --nodes=15 --qos=debug --time=30:00 --wrap="${REL}/mhm2.py $OPTS2 -o ${RUN_PREFIX}/rel-full && echo Good")
    - echo "Waiting for knl job $knl_job"
    - date
    - while /bin/true ; do sleep 120 ; date ; sacct=$(sacct -j $knl_job -o state -X -n 2>/dev/null || true) ; if [ -n "${sacct}" -a -z "$(echo "${sacct}" | grep ING)" ] ; then break ; fi ; done
    - echo "sacct $sacct"
    - sacct=$(sacct -j $knl_job -X -n)
    - echo "sacct $sacct"
    - cat slurm-${knl_job}.out
    - wasgood=$(echo "${sacct}" | grep -v '0:0' || true)
    - if [ -z "$wasgood" ] ; then  true ; else  echo "knl job ${knl_job} failed somehow - ${wasgood}"; false ; fi
    - if [ ! -f ${RUN_PREFIX}/rel/final_assembly.fasta ] ; then FAILED="${FAILED} Did not find final_assembly.fasta on rel" ; fi
    - ${REL}/check_asm_quality.py --asm-dir ${RUN_PREFIX}/rel --expected-quals ${REL}/../share/good-arctic-sample0.txt --refs ${ARCTIC}/arcticsynth-refs.fa || FAILED="${FAILED} Did not pass check_asm_quality.py"
    - echo "Waiting for second (full) job to finish ${knl_job2}"
    - while /bin/true ; do sleep 120 ; date ; sacct=$(sacct -j $knl_job2 -o state -X -n 2>/dev/null || true) ; if [ -n "${sacct}" -a -z "$(echo "${sacct}" | grep ING)" ] ; then break ; fi ; done
    - echo "sacct $sacct"
    - sacct=$(sacct -j $knl_job2 -X -n)
    - echo "sacct $sacct"
    - cat slurm-${knl_job2}.out
    - wasgood=$(echo "${sacct}" | grep -v '0:0' || true)
    - if [ -z "$wasgood" ] ; then  true ; else  echo "knl job ${knl_job2} failed somehow - ${wasgood}"; false ; fi
    - if [ ! -f ${RUN_PREFIX}/rel-full/final_assembly.fasta ] ; then FAILED="${FAILED} Did not find final_assembly.fasta on rel-full" ; fi
    - ${REL}/check_asm_quality.py --thres 0.015 --rna --asm-dir ${RUN_PREFIX}/rel-full --expected-quals ${REL}/../share/good-arcticsynth.txt --refs ${ARCTIC}/arcticsynth-refs.fa || FAILED="${FAILED} Did not pass check_asm_quality.py (full)"
    - if [ -z "$FAILED" ] ; then  true ; else echo "Something failed somehow - ${FAILED}" ; false ; fi
    - echo "Completed"





#
# hulk
#

HULK:build:
  stage: build
  tags:
    - HULK
  script:
    - set -e
    - set -x
    - git submodule init
    - git submodule sync
    - git submodule update
    - BASE=/work/gitlab-ci
    - CI_INSTALL=$BASE/ci-install-mhm2-upcxx-${HULK_UPCXX_VER}
    - export PATH=$CI_INSTALL/bin:/bin:/usr/bin:/usr/local/bin
    - export HIPMER_DATA=${BASE}/scratch/
    - mkdir -p ${HIPMER_DATA}
    - export SCRATCH=${BASE}/scratch/mhm2-${CI_COMMIT_SHORT_SHA}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_TAG}
    - export RUN_PREFIX=${SCRATCH}/runs
    - export GASNET_BACKTRACE=1
    - echo "Verifing and/or downloading test arctic data set"
    - export ARCTIC_URL=https://portal.nersc.gov/project/hipmer/MetaHipMer_datasets_12_2019/ArcticSynth/samples/
    - bash -c "[ -f ${HIPMER_DATA}/arcticsynth-refs.fa ] || ( curl -LO ${ARCTIC_URL}/arcticsynth-refs.fa.gz && gunzip arcticsynth-refs.fa.gz && mv arcticsynth-refs.fa ${HIPMER_DATA}/arcticsynth-refs.fa )"
    - bash -c "for i in 0 1 2 3 4 5 6 7 8 9 10 11 ; do [ -f ${HIPMER_DATA}/arctic_sample_\$i.fq ] || ( curl -LO ${ARCTIC_URL}/arctic_sample_\$i.fq.gz && gunzip arctic_sample_\$i.fq.gz && mv arctic_sample_\$i.fq ${HIPMER_DATA}/arctic_sample_\$i.fq ) ; done"
    - echo "Establishing all tests under BASE=$BASE and SCRATCH=$SCRATCH"
    - rm -rf ${SCRATCH}
    - mkdir -p ${SCRATCH}
    - chmod a+rx ${SCRATCH}
    - chmod g+s ${SCRATCH}
    - mkdir -p ${RUN_PREFIX}
    - exec >  >(tee -ia ${SCRATCH}/build.log)
    - exec 2> >(tee -ia ${SCRATCH}/build.err >&2)
    - echo "Logging to ${SCRATCH}/build.log and .err at $(date) on $(uname -n) in $(pwd)"  
    - export MHM2_SOURCE=$(pwd)
    - env
    - uname -a
    - pwd
    - find * -type d -ls
    - date
    - echo "Purging any old tests"
    - find ${BASE}/scratch -maxdepth 1  -name 'mhm*'  -mtime +4 -type d -exec rm -rf '{}' ';' || /bin/true
    - df -h
    - FAILED=""
    - echo "Checking for cmake, Berkeley UPC and UPC++"
    - which cmake && cmake --version || FAILED="${FAILED} cmake not found"
    - echo "Checking or building upcxx"
    - which upcxx || UPCXXVER=${HULK_UPCXX_VER} ./upcxx-utils/contrib/install_upcxx.sh $CI_INSTALL || FAILED="${FAILED} could not install upcxx"
    - upcxx --version || FAILED="${FAILED} no upcxx was found"
    - echo "Building all flavors"
    - mkdir -p ${RUN_PREFIX}
    - export GASNET_BACKTRACE=1
    - export INSTALL_PREFIX=${SCRATCH}
    - rm -rf $SCRATCH/build
    - mkdir -p $SCRATCH/build
    - cd $SCRATCH/build
    - echo "Building Debug"
    - cmake -DCMAKE_INSTALL_PREFIX=${INSTALL_PREFIX}/mhm2-dbg -DCMAKE_BUILD_TYPE=Debug ${MHM2_SOURCE} || FAILED="${FAILED} Could not configure Debug"
    - make -j 16 all check install || FAILED="${FAILED} Could not build Debug"
    - make clean
    - export UPCXX_CODEMODE=debug
    - echo "Building RelWithDebInfo with UPCXX_CODEMODE=$UPCXX_CODEMODE"
    - cmake -DCMAKE_INSTALL_PREFIX=${INSTALL_PREFIX}/mhm2-rwdi -DCMAKE_BUILD_TYPE=RelWithDebInfo ${MHM2_SOURCE} || FAILED="${FAILED} could not configure RelWithDebInfo"
    - make -j 16 all check install || FAILED="${FAILED} Cuold not build RelWithDebInfo"
    - make clean
    - unset UPCXX_CODEMODE
    - echo "Building Release"
    - cmake -DCMAKE_INSTALL_PREFIX=${INSTALL_PREFIX}/mhm2-rel -DCMAKE_BUILD_TYPE=Release ${MHM2_SOURCE} || FAILED="${FAILED} could not configure Release"
    - make -j 16 all check install || FAILED="${FAILED} Could not build Release"
    - echo "${FAILED}"
    - if [ -z "$FAILED" ] ; then  true ; else echo "Something failed somehow - ${FAILED}"; false ; fi
    - cd -
    - rm -rf $SCRATCH/build
    - echo "Completed"

    

HULK:validation:
  stage: validation
  tags:
    - HULK
  script:
    - set -e
    - set -x
    - BASE=/work/gitlab-ci
    - CI_INSTALL=$BASE/ci-install-mhm2-upcxx-${HULK_UPCXX_VER}
    - export PATH=$CI_INSTALL/bin:/bin:/usr/bin:/usr/local/bin
    - export HIPMER_DATA=${BASE}/scratch/
    - export SCRATCH=${BASE}/scratch/mhm2-${CI_COMMIT_SHORT_SHA}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_TAG}
    - export RUN_PREFIX=${SCRATCH}/runs
    - export INSTALL_PREFIX=${SCRATCH}
    - export GASNET_BACKTRACE=1
    - exec >  >(tee -ia ${SCRATCH}/validation.log)
    - exec 2> >(tee -ia ${SCRATCH}/validation.err >&2)
    - echo "Logging to ${SCRATCH}/validation.log and .err at $(date) on $(uname -n) in $(pwd)"  
    - echo "Validating all tests under BASE=$BASE and SCRATCH=$SCRATCH"
    - env
    - df -h
    - uname -a
    - pwd
    - date
    - upcxx --version
    - cd ${SCRATCH}
    - FAILED=""
    - reads=${HIPMER_DATA}/arctic_sample_0.fq 
    - export DBG=${INSTALL_PREFIX}/mhm2-dbg/bin/
    - export RWDI=${INSTALL_PREFIX}/mhm2-rwdi/bin/
    - export REL=${INSTALL_PREFIX}/mhm2-rel/bin/
    - echo "Starting RelWithDebInfo mhm2 on Arctic $reads"
    - if [ ! -f arctic_sample_0.fq -a -f $reads ] ; then ln -s $reads ; fi
    - if [ ! -f arcticsynth-refs.fa -a -f ${HIPMER_DATA}/arcticsynth-refs.fa ] ; then ln -s ${HIPMER_DATA}/arcticsynth-refs.fa ; fi
    - ${RWDI}/ci_asm_qual_test.sh || FAILED="${FAILED} Could not run ci_asm_qual_test"
    - if [ ! -f ./test-arctic-sample0/final_assembly.fasta ] ; then FAILED="${FAILED} Did not find final_assembly.fasta for rwdi in test-arctic-sample0" ; fi
    - mv test-arctic-sample0 ${RUN_PREFIX}/rwdi-test-arctic-sample0
    - echo "Starting debug run on with reduced workflow"
    - ${DBG}/mhm2.py -r $reads -o ${RUN_PREFIX}/dbg --kmer-lens 31,63 --checkpoint=no -v || FAILED="${FAILED} Could not run dbg"
    - echo "verify dbg results $(ls -la ${RUN_PREFIX}/dbg)"
    - if [ ! -f ${RUN_PREFIX}/dbg/final_assembly.fasta ] ; then FAILED="${FAILED} Did not find final_assembly.fasta on dbg" ; fi
    - ${DBG}/check_asm_quality.py --asm-dir ${RUN_PREFIX}/dbg --expected-quals ${DBG}/../share/good-arctic-sample0-k31k63.txt --refs ${HIPMER_DATA}/arcticsynth-refs.fa || echo "WARN did not pass check_asm_quality.py for dbg with reduced workflow k31k63"
    - if [ -z "$FAILED" ] ; then  true ; else echo "Something failed somehow - ${FAILED}"; false ; fi
    - echo "Completed"

HULK:accuracy:
  stage: accuracy
  tags:
    - HULK
  script:
    - set -e
    - set -x
    - git submodule init
    - git submodule sync
    - git submodule update
    - BASE=/work/gitlab-ci
    - CI_INSTALL=$BASE/ci-install-mhm2-upcxx-${HULK_UPCXX_VER}
    - export PATH=$CI_INSTALL/bin:/bin:/usr/bin:/usr/local/bin
    - export HIPMER_DATA=${BASE}/scratch/
    - export SCRATCH=${BASE}/scratch/mhm2-${CI_COMMIT_SHORT_SHA}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_TAG}
    - export RUN_PREFIX=${SCRATCH}/runs
    - export INSTALL_PREFIX=${SCRATCH}
    - export GASNET_BACKTRACE=1
    - exec >  >(tee -ia ${SCRATCH}/accuracy.log)
    - exec 2> >(tee -ia ${SCRATCH}/accuracy.err >&2)
    - echo "Logging to ${SCRATCH}/accuracy.log and .err at $(date) on $(uname -n) in $(pwd)"  
    - echo "Running accuracy tests under BASE=$BASE and SCRATCH=$SCRATCH"
    - env
    - df -h
    - uname -a
    - pwd
    - date
    - upcxx --version
    - cd ${SCRATCH}
    - FAILED=""
    - export REL=${INSTALL_PREFIX}/mhm2-rel/bin/
    - echo "Starting Release mhm2 on Arctic"
    - if [ ! -f arctic_sample_0.fq -a -f ${HIPMER_DATA}/arctic_sample_0.fq ] ; then ln -s ${HIPMER_DATA}/arctic_sample_0.fq ; fi
    - if [ ! -f arctic_sample_1.fq -a -f ${HIPMER_DATA}/arctic_sample_1.fq ] ; then ln -s ${HIPMER_DATA}/arctic_sample_1.fq ; fi
    - if [ ! -f arctic_sample_2.fq -a -f ${HIPMER_DATA}/arctic_sample_2.fq ] ; then ln -s ${HIPMER_DATA}/arctic_sample_2.fq ; fi
    - if [ ! -f arctic_sample_3.fq -a -f ${HIPMER_DATA}/arctic_sample_3.fq ] ; then ln -s ${HIPMER_DATA}/arctic_sample_3.fq ; fi
    - if [ ! -f arctic_sample_4.fq -a -f ${HIPMER_DATA}/arctic_sample_4.fq ] ; then ln -s ${HIPMER_DATA}/arctic_sample_4.fq ; fi
    - if [ ! -f arctic_sample_5.fq -a -f ${HIPMER_DATA}/arctic_sample_5.fq ] ; then ln -s ${HIPMER_DATA}/arctic_sample_5.fq ; fi
    - if [ ! -f arctic_sample_6.fq -a -f ${HIPMER_DATA}/arctic_sample_6.fq ] ; then ln -s ${HIPMER_DATA}/arctic_sample_6.fq ; fi
    - if [ ! -f arctic_sample_7.fq -a -f ${HIPMER_DATA}/arctic_sample_7.fq ] ; then ln -s ${HIPMER_DATA}/arctic_sample_7.fq ; fi
    - if [ ! -f arctic_sample_8.fq -a -f ${HIPMER_DATA}/arctic_sample_8.fq ] ; then ln -s ${HIPMER_DATA}/arctic_sample_8.fq ; fi
    - if [ ! -f arctic_sample_9.fq -a -f ${HIPMER_DATA}/arctic_sample_9.fq ] ; then ln -s ${HIPMER_DATA}/arctic_sample_9.fq ; fi
    - if [ ! -f arctic_sample_10.fq -a -f ${HIPMER_DATA}/arctic_sample_10.fq ] ; then ln -s ${HIPMER_DATA}/arctic_sample_10.fq ; fi
    - if [ ! -f arctic_sample_11.fq -a -f ${HIPMER_DATA}/arctic_sample_11.fq ] ; then ln -s ${HIPMER_DATA}/arctic_sample_11.fq ; fi
    - if [ ! -f arcticsynth-refs.fa -a -f ${HIPMER_DATA}/arcticsynth-refs.fa ] ; then ln -s ${HIPMER_DATA}/arcticsynth-refs.fa ; fi
    - ${REL}/ci_asm_qual_test.sh || FAILED="${FAILED} Could not run ci_asm_qual_test"
    - if [ ! -f ./test-arctic-sample0/final_assembly.fasta ] ; then FAILED="${FAILED} Did not find final_assembly.fasta on rel" ; fi
    - mv test-arctic-sample0 ${RUN_PREFIX}/rel-test-arctic-sample0
    - ${REL}/ci_asm_qual_test-full.sh || FAILED="${FAILED} Could not run ci_asm_qual_test-full"
    - if [ ! -f ./test-arctic-samples/final_assembly.fasta ] ; then FAILED="${FAILED} Did not find final_assembly.fasta on rel" ; fi
    - mv test-arctic-samples ${RUN_PREFIX}/rel-test-arctic-samples
    - if [ -z "$FAILED" ] ; then  true ; else echo "Something failed somehow - ${FAILED}"; false ; fi
    - echo "Completed"

after_script:
  - date
  - echo "Done"


